export type StyleNoteType = "naia_style_note" | "fashion_voice";

export interface DailyStyleNote {
  id: string;
  text: string;
  attribution: string;
  type: StyleNoteType;
  theme: string;
  verifiedSource: string | null;
  enabled: boolean;
}

export const dailyStyleNotes: DailyStyleNote[] = [
  {
    id: "nsn_01",
    text: "Colour is always a decision. What you reach for first tells you something true about today.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "colour",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_02",
    text: "Wearing one colour head to toe is the quietest kind of statement dressing there is.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "colour",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_03",
    text: "The right shade can do more for your face than anything in the makeup bag.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "colour",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_04",
    text: "Neutrals are not a compromise. In the right fabric, beige is the boldest colour in the room.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "colour",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_05",
    text: "A great silhouette asks nothing of the moment except that you stand in it.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "silhouette",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_06",
    text: "Proportion is the thing you feel before you can name it. Trust that instinct first.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "silhouette",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_07",
    text: "The waist is where a silhouette becomes personal. Define it or dissolve it — both are valid.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "silhouette",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_08",
    text: "Texture is what draws people in when they are already standing close.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "texture",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_09",
    text: "Linen in summer, cashmere in winter — the right fabric rewards the season and the body wearing it.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "texture",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_10",
    text: "A coat with weight says something that a lightweight one never quite manages.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "texture",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_11",
    text: "Some days you dress for others. Some days you dress entirely for yourself. Know the difference.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "mood",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_12",
    text: "The outfit that makes you stand a little taller before you leave is the right one.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "mood",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_13",
    text: "Dressing with intention on a grey morning can shift more than just the outfit.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "mood",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_14",
    text: "What you wear to meet someone for the first time matters more than most people admit.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "mood",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_15",
    text: "On a day when nothing feels right, a great fabric next to the skin changes something.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "mood",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_16",
    text: "Personal style is not about wearing what suits you. It is about knowing what you mean.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "identity",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_17",
    text: "The women with the most distinctive style are rarely wearing the newest thing.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "identity",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_18",
    text: "Style lives in the repetitions — the things you always reach for, season after season.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "identity",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_19",
    text: "Getting dressed with intention is preparation. What you wear sets the register for the day.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "intention",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_20",
    text: "The most powerful thing about a great outfit is that it makes certain decisions for you.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "intention",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_21",
    text: "There is always a reason you went back for the piece you almost put down.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "intention",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_22",
    text: "Confidence in clothes comes from knowing your own proportions well enough to stop second-guessing.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "confidence",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_23",
    text: "The outfit you hesitate over is rarely the one you should have worn.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "confidence",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_24",
    text: "A bad experiment is still worth something. You will not know your style without a few wrong turns.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "creativity",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_25",
    text: "The most well-dressed women have a wardrobe and a point of view — not just clothes.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "curation",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "nsn_26",
    text: "A considered outfit is not necessarily complicated. It simply knows what it is trying to say.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "intention",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "fv_01",
    text: "Buy less, choose well, make it last.",
    attribution: "Vivienne Westwood",
    type: "fashion_voice",
    theme: "curation",
    verifiedSource:
      "Guardian Live event: 'Vivienne Westwood on capitalism and clothing.' Guardian/YouTube, 30 October 2014. https://www.youtube.com/watch?v=cik7qDIBVPk",
    enabled: true,
  },
  {
    id: "nsn_27",
    text: "A well-chosen piece does not need to announce itself. It only needs to feel inevitable.",
    attribution: "nAia editorial note",
    type: "naia_style_note",
    theme: "intention",
    verifiedSource: null,
    enabled: true,
  },
  {
    id: "fv_04",
    text: "Fashion should be a form of escapism, and not a form of imprisonment.",
    attribution: "Alexander McQueen",
    type: "fashion_voice",
    theme: "escapism",
    verifiedSource:
      "WWD (Women's Wear Daily) interview with Alexander McQueen, ~2009. Published in memorial feature, 13 December 2010. https://wwd.com/fashion-news/fashion-features/newsmakers-alexander-mcqueen-3402279/",
    enabled: true,
  },
  {
    id: "fv_05",
    text: "I started to make fashion because I couldn't find anything to wear.",
    attribution: "Miuccia Prada",
    type: "fashion_voice",
    theme: "identity",
    verifiedSource:
      "W Magazine, interview with Miuccia Prada, 11 December 2015. https://www.wmagazine.com/story/miuccia-prada-ugly-fashion",
    enabled: true,
  },
  {
    id: "fv_06",
    text: "Overdressing is the greatest mistake.",
    attribution: "Karl Lagerfeld",
    type: "fashion_voice",
    theme: "style",
    verifiedSource:
      "WWD (Women's Wear Daily) interview with Karl Lagerfeld, 1975. Compiled in 'Lagerfeld Talks With WWD: Through the Years.' https://wwd.com/fashion-news/shows-reviews/lagerfeld-talks-with-wwd-through-the-years-1203037647/",
    enabled: true,
  },
];
