client_id = "a1c349cee05c491058a66830fb364500"
name = "naia-stylist"
application_url = "https://naia-stylist.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://naia-stylist.vercel.app/api/auth" ]

[app_proxy]
url = "https://naia-stylist.vercel.app"
subpath = "naia"
prefix = "apps"
