import { route, index } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("onboarding/step/:step", "routes/onboarding/step.$step.tsx"),
  route("onboarding/complete", "routes/onboarding/complete.tsx"),
  route("passport",            "routes/passport.tsx"),
  route("closet", "routes/closet._index.tsx"),
  route("style-me", "routes/style-me/_index.tsx"),
  route("style-me/mood", "routes/style-me/mood.tsx"),
  route("style-me/feeling", "routes/style-me/feeling.tsx"),
  route("style-me/comfort", "routes/style-me/comfort.tsx"),
  route("style-me/occasion", "routes/style-me/occasion.tsx"),
  route("style-me/source", "routes/style-me/source.tsx"),
  route("style-me/result", "routes/style-me/result.tsx"),
  route("api/customer-auth", "routes/api.customer-auth.jsx"),
  route("api/closet", "routes/api.closet.jsx"),
  route("api/style", "routes/api.style.jsx"),
  route("api/outfit-history", "routes/api.outfit-history.jsx"),
  route("api/outfit-rating", "routes/api.outfit-rating.jsx"),
  route("api/naia-products", "routes/api.naia-products.jsx"),
  route("api/wishlist", "routes/api.wishlist.jsx"),
  route("api/customer-profile", "routes/api.customer-profile.jsx"),
  route("api/confidence-dashboard", "routes/api.confidence-dashboard.jsx"),
  route("api/designer-stats", "routes/api.designer-stats.jsx"),
  route("api/generate-trend-report", "routes/api.generate-trend-report.jsx"),
  route("api/personalized-trends", "routes/api.personalized-trends.jsx"),
  route("trends", "routes/trends.jsx"),
  route("trends/:slug", "routes/trends.$slug.tsx"),
  route("trends/:slug/edit", "routes/trends.$slug.edit.tsx"),
  route("trends/:slug/lens/:lens", "routes/trends.$slug.lens.$lens.tsx"),
  route("stylist", "routes/stylist.jsx"),
  route("stylist-popup", "routes/stylist-popup.jsx"),
  route("api/wardrobe-insights", "routes/api.wardrobe-insights.jsx"),
  route("app", "routes/app.jsx", [
    index("routes/app._index.jsx"),
    route("designer-intelligence", "routes/app.designer-intelligence.jsx"),
  ]),
  route("auth/login", "routes/auth.login/route.jsx"),
  route("auth/shopify/login",    "routes/auth.shopify.login.tsx"),
  route("auth/shopify/callback", "routes/auth.shopify.callback.tsx"),
  route("auth/logout",           "routes/auth.logout.tsx"),
  route("auth/*", "routes/auth.$.jsx"),
  route("webhooks/app/scopes_update", "routes/webhooks.app.scopes_update.jsx"),
  route("webhooks/app/uninstalled", "routes/webhooks.app.uninstalled.jsx"),
  route("quick-style", "routes/quick-style/_index.tsx"),
  route("api/quick-style", "routes/api.quick-style.jsx"),
  route("full-style-profile", "routes/full-style-profile/_index.tsx"),
  route("api/full-style-profile", "routes/api.full-style-profile.jsx"),
  route("api/save-look", "routes/api.save-look.jsx"),
  route("buyskip", "routes/buyskip._index.tsx"),
  route("api/tryon", "routes/api.tryon.jsx"),
  route("api/body-scan", "routes/api.bodyscan.jsx"),
  route("account", "routes/account.jsx"),
  route("my-naia",                   "routes/my-naia._index.tsx"),
  route("my-naia/style-passport",    "routes/my-naia.style-passport.tsx"),
  route("my-naia/closet",            "routes/my-naia.closet.tsx"),
  route("my-naia/style-me",          "routes/my-naia.style-me.tsx"),
  route("my-naia/buy-or-skip",       "routes/my-naia.buy-or-skip.tsx"),
  route("my-naia/buying-decisions",  "routes/my-naia.buying-decisions.tsx"),
  route("my-naia/trend-edits",       "routes/my-naia.trend-edits.tsx"),
  route("my-naia/saved",             "routes/my-naia.saved.tsx"),
  route("my-naia/orders",            "routes/my-naia.orders.tsx"),
  route("my-naia/personalisation",   "routes/my-naia.personalisation.tsx"),
  route("my-naia/model",             "routes/my-naia.model.tsx"),
  route("my-naia/personal-analysis", "routes/my-naia.personal-analysis.tsx"),
  route("my-naia/what-naia-notices", "routes/my-naia.what-naia-notices.tsx"),
  route("my-naia/plan-usage",        "routes/my-naia.plan-usage.tsx"),
  route("my-naia/settings",          "routes/my-naia.settings.tsx"),
  route("my-naia/styleme/looks",     "routes/my-naia.styleme.looks._index.tsx"),
  route("my-naia/styleme/looks/:lookId", "routes/my-naia.styleme.looks.$lookId.tsx", [
    index("routes/my-naia.styleme.looks.$lookId._index.tsx"),
    route("feedback", "routes/my-naia.styleme.looks.$lookId.feedback.tsx"),
    route("refine",   "routes/my-naia.styleme.looks.$lookId.refine.tsx"),
    route("try-on",   "routes/my-naia.styleme.looks.$lookId.try-on.tsx"),
  ]),
  route("api/recommendation-feedback", "routes/api.recommendation-feedback.tsx"),
  route("api/post-wear-review", "routes/api.post-wear-review.tsx"),
  route("api/analyze-item", "routes/api.analyze-item.jsx"),
  route("api/cloudinary-signature", "routes/api.cloudinary-signature.jsx"),
  route("api/save-style-profile", "routes/api.save-style-profile.jsx"),
  route("api/customer-account-identity", "routes/api.customer-account-identity.jsx"),
  route("api/designer-dashboard", "routes/api.designer-dashboard.jsx"),
  route("api/seed-staging", "routes/api.seed-staging.jsx"),
  route("api/dev-login",    "routes/api.dev-login.tsx"),
  route("api/track_event", "routes/api.track_event.jsx"),
  route("dev/login",        "routes/dev.login.tsx"),
];
