import { route, index } from "@react-router/dev/routes";

export default [
  index("routes/stylist.jsx"),
  route("onboarding/step/:step", "routes/onboarding/step.$step.tsx"),
  route("onboarding/complete", "routes/onboarding/complete.tsx"),
  route("closet", "routes/closet._index.tsx"),
  route("style-me", "routes/style-me/_index.tsx"),
  route("style-me/mood", "routes/style-me/mood.tsx"),
  route("style-me/feeling", "routes/style-me/feeling.tsx"),
  route("style-me/occasion", "routes/style-me/occasion.tsx"),
  route("style-me/source", "routes/style-me/source.tsx"),
  route("style-me/result", "routes/style-me/result.tsx"),
  route("api/customer-auth", "routes/api.customer-auth.jsx"),
  route("api/closet", "routes/api.closet.jsx"),
  route("api/style", "routes/api.style.jsx"),
  route("api/outfit-history", "routes/api.outfit-history.jsx"),
  route("api/outfit-rating", "routes/api.outfit-rating.jsx"),
  route("api/naia-products", "routes/api.naia-products.jsx"),
  route("api/wishlist", "routes/api.wishlist.jsx"),
  route("api/customer-profile", "routes/api.customer-profile.jsx"),
  route("api/confidence-dashboard", "routes/api.confidence-dashboard.jsx"),
  route("stylist", "routes/stylist.jsx"),
  route("stylist-popup", "routes/stylist-popup.jsx"),
  route("app", "routes/app.jsx", [
    index("routes/app._index.jsx"),
  ]),
  route("auth/login", "routes/auth.login/route.jsx"),
  route("auth/*", "routes/auth.$.jsx"),
  route("webhooks/app/scopes_update", "routes/webhooks.app.scopes_update.jsx"),
  route("webhooks/app/uninstalled", "routes/webhooks.app.uninstalled.jsx"),
];