import { useState } from "react";
import jsPDF from "jspdf";

export default function TrendReports() {
  const [query, setQuery] = useState("");
  const [reportType, setReportType] = useState("seasonal");
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);

  async function generateReport() {
    if (!query.trim()) return;
    
    setLoading(true);
    setReport(null);

    try {
      const response = await fetch("/api/generate-trend-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query, reportType }),
      });

      const data = await response.json();
      setReport(data.report);
    } catch (err) {
      console.error(err);
      alert("Failed to generate report");
    } finally {
      setLoading(false);
    }
  }

  const reportTypes = [
    { id: "seasonal", label: "Seasonal Trends", placeholder: "e.g., Spring 2026 trends" },
    { id: "runway", label: "Fashion Week", placeholder: "e.g., Paris Fashion Week Fall 2026" },
    { id: "category", label: "Category Deep Dive", placeholder: "e.g., Designer bags, Denim" },
    { id: "color", label: "Color Trends", placeholder: "e.g., Spring 2026 colors" },
    { id: "brand", label: "Brand Profile", placeholder: "e.g., LOEWE Spring 2026" },
    { id: "accessories", label: "Accessory Watch", placeholder: "e.g., Spring 2026 bags" },
    { id: "emerging", label: "Emerging Brands", placeholder: "e.g., New designers to watch" },
  ];

  const currentType = reportTypes.find(t => t.id === reportType);

  const downloadReport = () => {
    const doc = new jsPDF();
    
    // Add nAia logo
    doc.setFontSize(24);
    doc.setFont(undefined, 'normal');
    doc.text('nAia', 105, 20, { align: 'center' });
    
    // Add report title
    doc.setFontSize(12);
    doc.text(currentType?.label.toUpperCase(), 105, 30, { align: 'center' });
    
    // Add query
    doc.setFontSize(10);
    doc.setTextColor(138, 127, 117);
    doc.text(query, 105, 38, { align: 'center' });
    
    // Add line
    doc.setDrawColor(26, 24, 22);
    doc.setLineWidth(0.5);
    doc.line(20, 45, 190, 45);
    
    // Reset text color
    doc.setTextColor(26, 24, 22);
    
    // Parse and add content
    let y = 55;
    const lines = report.split('\n');
    
    lines.forEach(line => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      
      if (line.startsWith('## ')) {
        // Section header
        doc.setFontSize(11);
        doc.setFont(undefined, 'bold');
        y += 8;
        doc.text(line.replace('## ', ''), 20, y);
        y += 6;
        doc.setFont(undefined, 'normal');
      } else if (line.match(/^\*\*.+\*\*$/)) {
        // Sub header
        doc.setFontSize(10);
        doc.setFont(undefined, 'bold');
        y += 5;
        doc.text(line.replace(/\*\*/g, ''), 20, y);
        y += 4;
        doc.setFont(undefined, 'normal');
      } else if (line.trim()) {
        // Regular text
        doc.setFontSize(9);
        const splitText = doc.splitTextToSize(line, 170);
        doc.text(splitText, 20, y);
        y += splitText.length * 5;
      } else {
        y += 3;
      }
    });
    
    // Add footer on last page
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(138, 127, 117);
      doc.text(`Generated by nAia Fashion Intelligence • ${new Date().toLocaleDateString()}`, 105, 285, { align: 'center' });
      doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    }
    
    // Download
    doc.save(`${query.replace(/\s+/g, '-').toLowerCase()}-trend-report.pdf`);
  };

  return (
    <div style={s.container}>
      <h1 style={s.title}>Fashion Intelligence</h1>
      <p style={s.subtitle}>Authoritative trend reports from runway, retail, and market signals</p>

      {/* Report Type Selector */}
      <div style={{ marginBottom: "24px" }}>
        <div style={s.label}>Report Type</div>
        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
          {reportTypes.map(type => (
            <button
              key={type.id}
              onClick={() => setReportType(type.id)}
              style={{
                ...s.typeButton,
                background: reportType === type.id ? "#1a1816" : "#eee9e2",
                color: reportType === type.id ? "#f5f2ee" : "#1a1816",
              }}
            >
              {type.label}
            </button>
          ))}
        </div>
      </div>

      {/* Input Section */}
      <div style={s.inputSection}>
        <input
          type="text"
          placeholder={currentType?.placeholder}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && generateReport()}
          style={s.input}
        />
        <button 
          onClick={generateReport} 
          disabled={loading || !query.trim()} 
          style={{
            ...s.button,
            opacity: (loading || !query.trim()) ? 0.5 : 1,
            cursor: (loading || !query.trim()) ? "not-allowed" : "pointer",
          }}
        >
          {loading ? "Generating..." : "Generate Report"}
        </button>
      </div>

      {loading && (
        <div style={s.loadingBox}>
          <p style={s.loadingText}>Analyzing fashion sources and generating {currentType?.label.toLowerCase()}...</p>
        </div>
      )}

      {report && (
        <div style={s.reportBox}>
          {/* Header */}
          <div style={s.reportHeader}>
            <div>
              <h2 style={s.reportTitle}>{currentType?.label}</h2>
              <p style={s.reportSubtitle}>{query}</p>
            </div>
            <div style={{ display: "flex", gap: "8px" }}>
              <button onClick={() => navigator.clipboard.writeText(report)} style={s.actionButton}>
                Copy
              </button>
              <button onClick={downloadReport} style={s.actionButton}>
                Download
              </button>
            </div>
          </div>

          {/* Report Content */}
          <div style={s.reportContent}>
            {report.split('\n').map((line, i) => {
              // Section headers (## )
              if (line.startsWith('## ')) {
                return <h3 key={i} style={s.sectionHeader}>{line.replace('## ', '')}</h3>;
              } 
              // Sub headers (**text**)
              else if (line.match(/^\*\*.+\*\*$/)) {
                return <h4 key={i} style={s.subHeader}>{line.replace(/\*\*/g, '')}</h4>;
              }
              // Bold inline text
              else if (line.includes('**')) {
                const parts = line.split(/(\*\*.*?\*\*)/g);
                return (
                  <p key={i} style={s.paragraph}>
                    {parts.map((part, idx) => 
                      part.startsWith('**') && part.endsWith('**') 
                        ? <strong key={idx}>{part.replace(/\*\*/g, '')}</strong>
                        : part
                    )}
                  </p>
                );
              }
              // List items
              else if (line.match(/^[\*\-]\s/)) {
                return <li key={i} style={s.listItem}>{line.replace(/^[\*\-]\s/, '')}</li>;
              }
              // Regular paragraphs
              else if (line.trim()) {
                return <p key={i} style={s.paragraph}>{line}</p>;
              }
              // Empty lines
              return <div key={i} style={{ height: '8px' }} />;
            })}
          </div>
        </div>
      )}
    </div>
  );
}

const s = {
  container: {
    maxWidth: "900px",
    margin: "0 auto",
    padding: "48px 24px",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
  },
  title: {
    fontSize: "36px",
    fontWeight: 400,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "#1a1816",
    margin: "0 0 8px",
  },
  subtitle: {
    fontSize: "15px",
    fontStyle: "italic",
    color: "#8a7f75",
    margin: "0 0 48px",
  },
  label: {
    fontSize: "11px",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: "#8a7f75",
    marginBottom: "12px",
  },
  typeButton: {
    padding: "10px 16px",
    fontSize: "12px",
    letterSpacing: "0.05em",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    border: "none",
    borderRadius: "2px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  inputSection: {
    display: "flex",
    gap: "12px",
    marginBottom: "32px",
  },
  input: {
    flex: 1,
    padding: "16px",
    fontSize: "15px",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    border: "1px solid #d4cfc9",
    borderRadius: "4px",
    outline: "none",
  },
  button: {
    padding: "16px 32px",
    fontSize: "13px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    background: "#1a1816",
    color: "#f5f2ee",
    border: "none",
    borderRadius: "4px",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  loadingBox: {
    padding: "32px",
    background: "#f5f2ee",
    borderRadius: "4px",
    textAlign: "center",
  },
  loadingText: {
    fontSize: "14px",
    color: "#8a7f75",
    fontStyle: "italic",
    margin: 0,
  },
  reportBox: {
    background: "#fff",
    border: "1px solid #d4cfc9",
    borderRadius: "4px",
    padding: "32px",
  },
  reportHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "32px",
    paddingBottom: "16px",
    borderBottom: "2px solid #1a1816",
  },
  reportTitle: {
    fontSize: "24px",
    fontWeight: 500,
    color: "#1a1816",
    margin: "0 0 4px",
  },
  reportSubtitle: {
    fontSize: "13px",
    color: "#8a7f75",
    margin: 0,
    fontStyle: "italic",
  },
  actionButton: {
    padding: "8px 16px",
    fontSize: "11px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    background: "transparent",
    color: "#1a1816",
    border: "1px solid #1a1816",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  reportContent: {
    lineHeight: 1.8,
  },
  sectionHeader: {
    fontSize: "16px",
    fontWeight: 500,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#1a1816",
    margin: "32px 0 16px",
    paddingBottom: "8px",
    borderBottom: "1px solid #e8e4df",
  },
  subHeader: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#4a4540",
    margin: "16px 0 8px",
  },
  paragraph: {
    fontSize: "15px",
    color: "#1a1816",
    margin: "0 0 12px",
    lineHeight: 1.7,
  },
  listItem: {
    fontSize: "15px",
    color: "#1a1816",
    margin: "0 0 8px 20px",
    lineHeight: 1.7,
  },
};