import { useState } from "react";

export default function TrendReports() {
  const [query, setQuery] = useState("");
  const [reportType, setReportType] = useState("seasonal");
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);

  async function generateReport() {
    if (!query.trim()) return;
    
    setLoading(true);
    setReport(null);

    try {
      const response = await fetch("/api/generate-trend-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query, reportType }),
      });

      const data = await response.json();
      setReport(data.report);
    } catch (err) {
      console.error(err);
      alert("Failed to generate report");
    } finally {
      setLoading(false);
    }
  }

  const reportTypes = [
    { id: "seasonal", label: "Seasonal Trends", placeholder: "e.g., Spring 2026 trends" },
    { id: "runway", label: "Fashion Week", placeholder: "e.g., Paris Fashion Week Fall 2026" },
    { id: "category", label: "Category Deep Dive", placeholder: "e.g., Designer bags, Denim" },
    { id: "color", label: "Color Trends", placeholder: "e.g., Spring 2026 colors" },
    { id: "brand", label: "Brand Profile", placeholder: "e.g., LOEWE Spring 2026" },
    { id: "accessories", label: "Accessory Watch", placeholder: "e.g., Spring 2026 bags" },
    { id: "emerging", label: "Emerging Brands", placeholder: "e.g., New designers to watch" },
  ];

  const currentType = reportTypes.find(t => t.id === reportType);

  const downloadReport = async () => {
    try {
      // For now, let's create a styled HTML version and let the browser print to PDF
      const printWindow = window.open('', '_blank');
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>${query} - Trend Report</title>
          <style>
            @page { margin: 2cm; }
            body {
              font-family: Georgia, serif;
              color: #1a1816;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px;
            }
            .header {
              text-align: center;
              margin-bottom: 40px;
              padding-bottom: 20px;
              border-bottom: 2px solid #1a1816;
            }
            .logo {
              font-size: 32px;
              font-weight: 300;
              letter-spacing: 0.2em;
              margin-bottom: 10px;
            }
            .report-title {
              font-size: 20px;
              text-transform: uppercase;
              letter-spacing: 0.1em;
              margin: 10px 0;
            }
            .query {
              font-size: 14px;
              font-style: italic;
              color: #8a7f75;
            }
            h2 {
              font-size: 16px;
              text-transform: uppercase;
              letter-spacing: 0.1em;
              margin: 30px 0 15px;
              padding-bottom: 8px;
              border-bottom: 1px solid #e8e4df;
            }
            h3 {
              font-size: 14px;
              font-weight: 500;
              margin: 15px 0 8px;
            }
            p, li {
              font-size: 14px;
              line-height: 1.7;
              margin: 0 0 12px;
            }
            li {
              margin-left: 20px;
            }
            .footer {
              margin-top: 50px;
              padding-top: 20px;
              border-top: 1px solid #e8e4df;
              text-align: center;
              font-size: 12px;
              color: #8a7f75;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo">nAia</div>
            <div class="report-title">${currentType?.label}</div>
            <div class="query">${query}</div>
          </div>
          <div class="content">
            ${report.split('\n').map(line => {
              if (line.startsWith('## ')) {
                return `<h2>${line.replace('## ', '')}</h2>`;
              } else if (line.match(/^\*\*.+\*\*$/)) {
                return `<h3>${line.replace(/\*\*/g, '')}</h3>`;
              } else if (line.includes('**')) {
                return `<p>${line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</p>`;
              } else if (line.match(/^[\*\-]\s/)) {
                return `<li>${line.replace(/^[\*\-]\s/, '')}</li>`;
              } else if (line.trim()) {
                return `<p>${line}</p>`;
              }
              return '';
            }).join('\n')}
          </div>
          <div class="footer">
            Generated by nAia Fashion Intelligence • ${new Date().toLocaleDateString()}
          </div>
        </body>
        </html>
      `);
      printWindow.document.close();
      
      // Wait a moment then trigger print dialog
      setTimeout(() => {
        printWindow.print();
      }, 250);
    } catch (err) {
      console.error('PDF generation error:', err);
      alert('Failed to generate PDF');
    }
  };

  return (
    <div style={s.container}>
      <h1 style={s.title}>Fashion Intelligence</h1>
      <p style={s.subtitle}>Authoritative trend reports from runway, retail, and market signals</p>

      {/* Report Type Selector */}
      <div style={{ marginBottom: "24px" }}>
        <div style={s.label}>Report Type</div>
        <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
          {reportTypes.map(type => (
            <button
              key={type.id}
              onClick={() => setReportType(type.id)}
              style={{
                ...s.typeButton,
                background: reportType === type.id ? "#1a1816" : "#eee9e2",
                color: reportType === type.id ? "#f5f2ee" : "#1a1816",
              }}
            >
              {type.label}
            </button>
          ))}
        </div>
      </div>

      {/* Input Section */}
      <div style={s.inputSection}>
        <input
          type="text"
          placeholder={currentType?.placeholder}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && generateReport()}
          style={s.input}
        />
        <button 
          onClick={generateReport} 
          disabled={loading || !query.trim()} 
          style={{
            ...s.button,
            opacity: (loading || !query.trim()) ? 0.5 : 1,
            cursor: (loading || !query.trim()) ? "not-allowed" : "pointer",
          }}
        >
          {loading ? "Generating..." : "Generate Report"}
        </button>
      </div>

      {loading && (
        <div style={s.loadingBox}>
          <p style={s.loadingText}>Analyzing fashion sources and generating {currentType?.label.toLowerCase()}...</p>
        </div>
      )}

      {report && (
        <div style={s.reportBox}>
          {/* Header */}
          <div style={s.reportHeader}>
            <div>
              <h2 style={s.reportTitle}>{currentType?.label}</h2>
              <p style={s.reportSubtitle}>{query}</p>
            </div>
            <div style={{ display: "flex", gap: "8px" }}>
              <button onClick={() => navigator.clipboard.writeText(report)} style={s.actionButton}>
                Copy
              </button>
              <button onClick={downloadReport} style={s.actionButton}>
                Download
              </button>
            </div>
          </div>

          {/* Report Content */}
          <div style={s.reportContent}>
            {report.split('\n').map((line, i) => {
              // Section headers (## )
              if (line.startsWith('## ')) {
                return <h3 key={i} style={s.sectionHeader}>{line.replace('## ', '')}</h3>;
              } 
              // Sub headers (**text**)
              else if (line.match(/^\*\*.+\*\*$/)) {
                return <h4 key={i} style={s.subHeader}>{line.replace(/\*\*/g, '')}</h4>;
              }
              // Bold inline text
              else if (line.includes('**')) {
                const parts = line.split(/(\*\*.*?\*\*)/g);
                return (
                  <p key={i} style={s.paragraph}>
                    {parts.map((part, idx) => 
                      part.startsWith('**') && part.endsWith('**') 
                        ? <strong key={idx}>{part.replace(/\*\*/g, '')}</strong>
                        : part
                    )}
                  </p>
                );
              }
              // List items
              else if (line.match(/^[\*\-]\s/)) {
                return <li key={i} style={s.listItem}>{line.replace(/^[\*\-]\s/, '')}</li>;
              }
              // Regular paragraphs
              else if (line.trim()) {
                return <p key={i} style={s.paragraph}>{line}</p>;
              }
              // Empty lines
              return <div key={i} style={{ height: '8px' }} />;
            })}
          </div>
        </div>
      )}
    </div>
  );
}

const s = {
  container: {
    maxWidth: "900px",
    margin: "0 auto",
    padding: "48px 24px",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
  },
  title: {
    fontSize: "36px",
    fontWeight: 400,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "#1a1816",
    margin: "0 0 8px",
  },
  subtitle: {
    fontSize: "15px",
    fontStyle: "italic",
    color: "#8a7f75",
    margin: "0 0 48px",
  },
  label: {
    fontSize: "11px",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: "#8a7f75",
    marginBottom: "12px",
  },
  typeButton: {
    padding: "10px 16px",
    fontSize: "12px",
    letterSpacing: "0.05em",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    border: "none",
    borderRadius: "2px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  inputSection: {
    display: "flex",
    gap: "12px",
    marginBottom: "32px",
  },
  input: {
    flex: 1,
    padding: "16px",
    fontSize: "15px",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    border: "1px solid #d4cfc9",
    borderRadius: "4px",
    outline: "none",
  },
  button: {
    padding: "16px 32px",
    fontSize: "13px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    background: "#1a1816",
    color: "#f5f2ee",
    border: "none",
    borderRadius: "4px",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  loadingBox: {
    padding: "32px",
    background: "#f5f2ee",
    borderRadius: "4px",
    textAlign: "center",
  },
  loadingText: {
    fontSize: "14px",
    color: "#8a7f75",
    fontStyle: "italic",
    margin: 0,
  },
  reportBox: {
    background: "#fff",
    border: "1px solid #d4cfc9",
    borderRadius: "4px",
    padding: "32px",
  },
  reportHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "32px",
    paddingBottom: "16px",
    borderBottom: "2px solid #1a1816",
  },
  reportTitle: {
    fontSize: "24px",
    fontWeight: 500,
    color: "#1a1816",
    margin: "0 0 4px",
  },
  reportSubtitle: {
    fontSize: "13px",
    color: "#8a7f75",
    margin: 0,
    fontStyle: "italic",
  },
  actionButton: {
    padding: "8px 16px",
    fontSize: "11px",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    fontFamily: '"Cormorant Garamond", Georgia, serif',
    background: "transparent",
    color: "#1a1816",
    border: "1px solid #1a1816",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  reportContent: {
    lineHeight: 1.8,
  },
  sectionHeader: {
    fontSize: "16px",
    fontWeight: 500,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#1a1816",
    margin: "32px 0 16px",
    paddingBottom: "8px",
    borderBottom: "1px solid #e8e4df",
  },
  subHeader: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#4a4540",
    margin: "16px 0 8px",
  },
  paragraph: {
    fontSize: "15px",
    color: "#1a1816",
    margin: "0 0 12px",
    lineHeight: 1.7,
  },
  listItem: {
    fontSize: "15px",
    color: "#1a1816",
    margin: "0 0 8px 20px",
    lineHeight: 1.7,
  },
};